import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_LOCAL = join(ROOT, '.env.local');
const ENV_EXAMPLE = join(ROOT, '.env.example');
const DB_NAME = 'newkhangdone-approval';
const REGION = 'ap-southeast-1';
const CLI = ['npx', '@upstash/cli@latest'];

const args = process.argv.slice(2);
const permanent = args.includes('--permanent');
const skipVercel = args.includes('--no-vercel');

function runCli(subcommand, cliArgs = [], { json = false } = {}) {
    const command = [...CLI, ...subcommand, ...cliArgs].join(' ');
    const result = spawnSync(command, {
        cwd: ROOT,
        encoding: 'utf8',
        shell: true,
        stdio: ['inherit', 'pipe', 'pipe']
    });

    if (result.status !== 0) {
        const err = (result.stderr || result.stdout || '').trim();
        throw new Error(err || `Command failed: upstash ${subcommand.join(' ')}`);
    }

    const output = (result.stdout || '').trim();
    return json && output ? JSON.parse(output) : output;
}

function parseStartRedisMarkdown(markdown) {
    const endpoint = markdown.match(/\*\*Endpoint:\*\*\s*(.+)/)?.[1]?.trim();
    const token = markdown.match(/\*\*Token:\*\*\s*(.+)/)?.[1]?.trim();
    const databaseId = markdown.match(/\*\*Database ID:\*\*\s*(.+)/)?.[1]?.trim();
    const claimUrl = markdown.match(/(https:\/\/upstash\.com\/start-redis\/console\/[^\s)]+)/)?.[1]?.trim();

    if (!endpoint || !token) {
        throw new Error('Could not parse Upstash start-redis output.');
    }

    return { endpoint, token, databaseId, claimUrl };
}

function pickCredentials(payload) {
    const endpoint =
        payload.endpoint ??
        payload.rest_url ??
        payload.restUrl ??
        payload.database?.endpoint ??
        payload.database?.rest_url;

    const token =
        payload.rest_token ??
        payload.restToken ??
        payload.token ??
        payload.database?.rest_token ??
        payload.database?.restToken;

    if (!endpoint || !token) {
        throw new Error('Upstash response did not include REST credentials.');
    }

    return { endpoint, token };
}

async function createPermanentDatabase() {
    let listPayload;

    try {
        listPayload = runCli(['redis', 'list'], [], { json: true });
    } catch {
        console.log('\nChua dang nhap Upstash.');
        console.log('Chay:  npx @upstash/cli login');
        console.log('Roi chay lai:  pnpm setup:redis --permanent\n');
        console.log('Hoac dung Redis tam 72h (khong can tai khoan):  pnpm setup:redis\n');
        process.exit(1);
    }

    const databases = Array.isArray(listPayload) ? listPayload : (listPayload.databases ?? listPayload.items ?? []);
    let database = databases.find((item) => item.name === DB_NAME);

    if (!database) {
        console.log(`Tao Redis vinh vien "${DB_NAME}" (${REGION})...`);
        database = runCli(['redis', 'create', '--name', DB_NAME, '--region', REGION], [], { json: true });
    } else {
        console.log(`Dung lai Redis da co: "${DB_NAME}"`);
    }

    const dbId = database.database_id ?? database.id ?? database.db_id;
    const details = runCli(['redis', 'get', '--db-id', dbId], [], { json: true });
    return pickCredentials(details);
}

async function createTemporaryDatabase() {
    console.log('Tao Redis tam (72 gio, khong can tai khoan Upstash)...');
    const markdown = runCli(['start-redis', '--user-agent', 'cursor']);
    return parseStartRedisMarkdown(markdown);
}

function readEnvFile(path) {
    if (!existsSync(path)) return {};

    const entries = {};
    for (const line of readFileSync(path, 'utf8').split('\n')) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const idx = trimmed.indexOf('=');
        if (idx === -1) continue;
        entries[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
    }
    return entries;
}

function writeEnvLocal(credentials, extra = {}) {
    const current = readEnvFile(ENV_LOCAL);
    const example = readEnvFile(ENV_EXAMPLE);

    const merged = {
        ...example,
        ...current,
        UPSTASH_REDIS_REST_URL: credentials.endpoint,
        UPSTASH_REDIS_REST_TOKEN: credentials.token,
        ...extra
    };

    const lines = [
        '# Auto-generated by pnpm setup:redis',
        `UPSTASH_REDIS_REST_URL=${merged.UPSTASH_REDIS_REST_URL}`,
        `UPSTASH_REDIS_REST_TOKEN=${merged.UPSTASH_REDIS_REST_TOKEN}`
    ];

    if (merged.TELEGRAM_BOT_TOKEN) lines.push(`TELEGRAM_BOT_TOKEN=${merged.TELEGRAM_BOT_TOKEN}`);
    if (merged.TELEGRAM_CHAT_ID) lines.push(`TELEGRAM_CHAT_ID=${merged.TELEGRAM_CHAT_ID}`);

    writeFileSync(ENV_LOCAL, `${lines.join('\n')}\n`, 'utf8');
    console.log(`\nDa ghi ${ENV_LOCAL}`);
}

function hasVercelProject() {
    return existsSync(join(ROOT, '.vercel', 'project.json'));
}

function pushVercelEnv(name, value) {
    for (const target of ['production', 'preview', 'development']) {
        const result = spawnSync(`npx vercel env add ${name} ${target} --force`, {
            cwd: ROOT,
            input: value,
            encoding: 'utf8',
            shell: true,
            stdio: ['pipe', 'pipe', 'pipe']
        });

        if (result.status !== 0) {
            const message = (result.stderr || result.stdout || '').trim();
            throw new Error(message || `vercel env add ${name} ${target} failed`);
        }
    }
}

function syncVercel(credentials) {
    if (skipVercel) return;

    if (!hasVercelProject()) {
        console.log('\nChua link Vercel project (.vercel/project.json).');
        console.log('Neu muon tu dong day env len Vercel:');
        console.log('  npx vercel link');
        console.log('  pnpm setup:redis\n');
        return;
    }

    console.log('\nDang day bien moi truong len Vercel...');
    pushVercelEnv('UPSTASH_REDIS_REST_URL', credentials.endpoint);
    pushVercelEnv('UPSTASH_REDIS_REST_TOKEN', credentials.token);
    console.log('Da cap nhat UPSTASH_REDIS_* tren Vercel (production/preview/development).');
    console.log('Chay "npx vercel --prod" de deploy lai neu can.');
}

async function main() {
    console.log('=== Setup Redis cho duyet tay ===\n');

    const credentials = permanent ? await createPermanentDatabase() : await createTemporaryDatabase();

    writeEnvLocal(credentials);
    syncVercel(credentials);

    console.log('\nXong. Redis REST URL:', credentials.endpoint);

    if (credentials.claimUrl) {
        console.log('\nRedis tam 72 gio. De giu lau dai, mo link Claim:');
        console.log(credentials.claimUrl);
        console.log('\nHoac tao Redis vinh vien:  pnpm setup:redis --permanent');
    } else {
        console.log('\nRedis vinh vien da san sang.');
    }
}

main().catch((error) => {
    console.error('\nLoi:', error.message);
    process.exit(1);
});
